"""accounts, invite codes, sessions, audit log

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 21:08:04.891597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'physiotherapist', 'admin', name='account_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR mobile IS NOT NULL', name='ck_accounts_has_identifier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('subject_key', sa.String(length=80), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_subject_time', 'login_attempts', ['subject_key', 'created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_auth_sessions_account', 'auth_sessions', ['account_id'], unique=False)
    op.create_index('ix_auth_sessions_previous_hash', 'auth_sessions', ['previous_refresh_token_hash'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('physiotherapist_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['physiotherapist_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_invite_codes_physiotherapist', 'invite_codes', ['physiotherapist_id'], unique=False)
    op.create_table('patient_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('physiotherapist_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['physiotherapist_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_assignments_physiotherapist', 'patient_assignments', ['physiotherapist_id'], unique=False)
    op.create_index('uq_patient_assignments_active', 'patient_assignments', ['patient_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_patient_assignments_active', table_name='patient_assignments', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('ix_patient_assignments_physiotherapist', table_name='patient_assignments')
    op.drop_table('patient_assignments')
    op.drop_index('ix_invite_codes_physiotherapist', table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index('ix_auth_sessions_previous_hash', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_account', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_login_attempts_subject_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    sa.Enum(name='account_role').drop(op.get_bind())
